MyWorkoutTracker/MyWorkoutTracker/Controllers/FinalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWorkoutTracker.Models;

namespace MyWorkoutTracker.Controllers
{
    [Authorize(Roles = "User,Administrator")]
    public class FinalController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Final
        public ActionResult Index()
        {
            var id = (int)Session["ID"];
            Person person = db.People.Find(id);
            Session["ID"] = person.id;
            return View(person);
        }

        public ActionResult Delete()
        {
            var id = (int)Session["ID"];
            Person person = db.People.Find(id);

            person.Exercises.Clear();

            person.Foods.Clear();
            db.SaveChanges();

            return RedirectToAction("Details/" + person.id, "People");
        }
    }
}

MyWorkoutTracker/MyWorkoutTracker/Views/Final/Index.cshtml
@model  MyWorkoutTracker.Models.Person
@{
    ViewBag.Title = "Index";
    int i = 0;
}
<body style="background: linear-gradient(to bottom, #2e2c2c 10%, #ffffff 100%);color:black">
    <div class="text-center" style="margin-top: 15px; margin-bottom:15px;">
        <img src="~/Images/Logo.jpg" class="text-center img-thumbnail" style="width: 20%; border-radius:50%;" />
    </div>
    <br />
    <div class="row">
        <div class="col-lg-6">
            <table class="table" id="tabela" style="color:#145214">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Exercises)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Exercises)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="col-lg-6">
            <table class="table" id="tabela" style="color:#145214">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Foods)
                        </th>
                        <th>
                            Enter quantity in grams
                        </th>
                        <th>
                            Calories per gram
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Foods)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <input onblur="findTotalCalorieIntake()" name="food" type="number" min="0" id="@item.Kcal" />

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Kcal)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6" style="color:#145214">

            Enter how much time you spent doint the whole exercise: <input onblur="findTotal()" id="time" name="time" type="number" min="0" class="form-control" />
            <br />
            Select the intensity of the workout:
           
            <select class="intensity form-control" id="WorkoutIntesity" name="WorkoutIntesity" onblur="findTotal()">
                <option>Select Intesity</option>
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>
            </select>
            <br />
            Total burned calories:<input type="text" name="total" id="total" class="form-control" />
        </div>
        <div class="col-lg-6" style="color:#145214">
            Total intake of calories:<input type="text" name="totalIntake" id="totalIntake" class="form-control" />
            <br />
            @Html.ActionLink("Clear Lists", "Delete", "Final", new { @class = "btn btn-success" })
        </div>
    </div>
    

    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
</body>
<script type="text/javascript">
    document.getElementById('total').readOnly = true;
    document.getElementById('totalIntake').readOnly = true;

    
    function findTotal() {
        var finish = null;
        var intensity = $('#WorkoutIntesity').find(":selected").text();
        var TotalTime = document.getElementById('time').value;
        if (intensity == "Low") {
            finish = parseFloat(400 / 60) * parseFloat(TotalTime);
        } else if (intensity == "Medium") {
            finish = parseFloat(600 / 60) * parseFloat(TotalTime);
        } else {
            finish = parseFloat(800 / 60) * parseFloat(TotalTime);
        }
        document.getElementById('total').value = finish;
    }
</script>

<script type="text/javascript">
    function findTotalCalorieIntake() {

                var arr = document.getElementsByName('food');
                var tot = 0;
                for (var i = 0; i < arr.length; i++) {
                    if (parseInt(arr[i].value))
                        tot += parseFloat(arr[i].value) * parseFloat(arr[i].id);
                }
                document.getElementById('totalIntake').value = tot;
            }
</script>